### ISSUE TITLE
Qpython hello world

### ISSUE THREAD

**Issue by jnoordzij87** [qpython-android/qpython#106]
Hi

Im new to qpython and just tried my first hello world.

Print "hello"
Print "whats your name?"
myname = input ()
Print "hello" + myname

I get the following error 

/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/jos/hello.py" && exit
/qpython/jos/hello.py" && exit           <
hello
what is your name?
Jos
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/jos/hello.py", line 3, in <module>
    myname = input()
  File "<string>", line 1, in <module>
NameError: name 'Jos' is not defined
1|u0_a292@E6853:/ $

Seems like it is not picking up the input () command. But then again, im a noob. 

Am i doing something wrong? 

Thanks in advance.

**Comment by jnoordzij87** [comment]
I am sorry i was confusing Al to use version 2 Python but he is using 3. Mybad

**Comment by jnoordzij87** [comment]
The ultimate newbie question i suppose :)
