### ISSUE TITLE
Python 3.2 makefile not included in clean install of qpython3, which causes pip to always fail

### ISSUE THREAD

**Issue by TheRektafire** [qpython-android/qpython#129]
Whenever i try to install a package with pip it gives an error code 1 and states that "storage/emulated/0/qpython/lib/python3.2/config3.2m/makefile" can't be found. And this is from a clean install. Which is kind of annoying and should be fixed. I am on a Samsung Galaxy J3 with Android 6.0, uprooted.

Full dump of pip.log

Downloading/unpacking distro

  Getting page https://pypi.python.org/simple/distro
  URLs to search for versions for distro:
  * https://pypi.python.org/simple/distro/
  Getting page https://pypi.python.org/simple/distro/
  Analyzing links from page https://pypi.org/simple/distro/
    Found link https://files.pythonhosted.org/packages/b7/ff/876ab097c769295f880c9056d09c934f5c7c4c6054df1a83953b73f85f73/distro-0.5.0.tar.gz#sha256=873b3a87a5c69913d3d722d70370ffad65bbd21740770d5e6ef5acc2387f2174 (from https://pypi.org/simple/distro/), version: 0.5.0
    Found link https://files.pythonhosted.org/packages/01/9c/ea1b152ac247a5747598168b88ae82eb742461e2e556262ae741e69bd30f/distro-0.6.0.tar.gz#sha256=671757a4438aa813723984e0e5800de76af6aef12e7bb2468f648d155a1472f6 (from https://pypi.org/simple/distro/), version: 0.6.0
    Found link https://files.pythonhosted.org/packages/15/97/e2d5863d03cd01b250e51117be031dab2ec0916efc5915f5094f5fd7602c/distro-1.0.0.tar.gz#sha256=bf8ac22bb0e2a7dcfd6e5d238fb2b009f71a78bb773e7d420605b27871f95754 (from https://pypi.org/simple/distro/), version: 1.0.0
    Skipping link https://files.pythonhosted.org/packages/80/4e/22225a92917ebf7780ddb972e14add3d710c718ac00f152c7811ca07b4f3/distro-1.0.1-py2.py3-none-any.whl#sha256=94977c5b2c225e2f6552c8773bfe6b76b55521add9fc52960de4b24bbb16c9df (from https://pypi.org/simple/distro/); unknown archive format: .whl
    Found link https://files.pythonhosted.org/packages/0d/c5/de784640f0b434799d6eecb63baea9c099e7fe6c0908b4036c3a5200c281/distro-1.0.1.tar.gz#sha256=b940995858ec63a29a272ddf7916818bb5cccb9297928fb8230fd37a146b1f26 (from https://pypi.org/simple/distro/), version: 1.0.1
    Skipping link https://files.pythonhosted.org/packages/64/4d/2d450e0a6dcf394bc0c581e499a66e00d255938f74db6b15748373d36cc4/distro-1.0.2-py2.py3-none-any.whl#sha256=b62e8e0cc6c7b5f688e7034358c770adb5b338c866100be0d62a8a38e5772767 (from https://pypi.org/simple/distro/); unknown archive format: .whl
    Found link https://files.pythonhosted.org/packages/42/ac/89b295d2784d450ca71ac6f3665cb90f07afe0928e4436af627983faf2b1/distro-1.0.2.tar.gz#sha256=77ec1f3695eed4dcda4e0e89d04dfcd91a20d3080d34f9294c5da47235382745 (from https://pypi.org/simple/distro/), version: 1.0.2
    Skipping link https://files.pythonhosted.org/packages/4a/c2/50dbfaac03c14b8e155e4329553ef1f73a51a5c3cece8fb62e849c0785ed/distro-1.0.3-py2.py3-none-any.whl#sha256=f9fe1179ef339cc9456f21f9445d92112ec8f5dbc639ea73ca76b3141de7cc93 (from https://pypi.org/simple/distro/); unknown archive format: .whl
    Found link https://files.pythonhosted.org/packages/df/65/a8a94c1e069cf5f5bffab2a6b88d5a78089c60f2916e96d18b625731f191/distro-1.0.3.tar.gz#sha256=2d99cdfd48a72f5e5f8545a03ee320521af43bfc53d471f4adfaea3ec36fb2ce (from https://pypi.org/simple/distro/), version: 1.0.3
    Skipping link https://files.pythonhosted.org/packages/b5/82/363544dcfa3e7f1478e6839aa929a95ac6e1b0c3b56a277e6a6ef3ace2c9/distro-1.0.4-py2.py3-none-any.whl#sha256=c6bbd046334248383199440a6163dcf9557585b6c192985020abefda84a4814c (from https://pypi.org/simple/distro/); unknown archive format: .whl
    Found link https://files.pythonhosted.org/packages/aa/4e/2cf3e7f67abe101c053af838f8d9b3b5911fd9360b498a1ba66a23d1ed46/distro-1.0.4.tar.gz#sha256=9b000b0d637bb0cbd130a7a4835681e6993e309a85564dfea9d884825fe46954 (from https://pypi.org/simple/distro/), version: 1.0.4
    Skipping link https://files.pythonhosted.org/packages/b0/55/29bfd4d4d4149e860ed01aa446108eb17b240997b746c06a2d0c8ce04f69/distro-1.1.0-py2.py3-none-any.whl#sha256=f0e43d555fd45eda71eb474c2927c17b75e0673bf13f90f70bdce5b1a90cf0c5 (from https://pypi.org/simple/distro/); unknown archive format: .whl
    Found link https://files.pythonhosted.org/packages/21/7b/14198029b49abdf80c6b8aadd9862f863b683dc4d3c2418f01bc6fad9fa3/distro-1.1.0.tar.gz#sha256=722054925f339a39ca411a8c7079f390a41d42c422697bedf228f1a9c46ac1ee (from https://pypi.org/simple/distro/), version: 1.1.0
    Skipping link https://files.pythonhosted.org/packages/c1/e4/933159b5f7f9f5b7ae463e76f58da84a30d0943ab3c162c366a9ad95f01e/distro-1.2.0-py2.py3-none-any.whl#sha256=49945b5696240ac95021bd4908c1ace423db3e5ecac05a85497e4b3662750766 (from https://pypi.org/simple/distro/); unknown archive format: .whl
    Found link https://files.pythonhosted.org/packages/b2/2e/e4b8b7f947465474e58bc9dbaa6ea8c4b4cc9e845711c0fc2f66601e464b/distro-1.2.0.tar.gz#sha256=d94370e43b676ac44fbe1ab68ca903a6147eaba3a9e8eff85b2c05556a455b76 (from https://pypi.org/simple/distro/), version: 1.2.0
    Skipping link https://files.pythonhosted.org/packages/f6/b1/ba5a96bccd3496241d8908164b9502a129156443cdd5acbdbf04a90b7a09/distro-1.3.0-py2.py3-none-any.whl#sha256=6ec8e539cf412830e5ccf521aecf879f2c7fcf60ce446e33cd16eef1ed8a0158 (from https://pypi.org/simple/distro/); unknown archive format: .whl
    Found link https://files.pythonhosted.org/packages/d2/42/3b059929a920cd9d4e91e7a5e35f0d2ed75211f8f4e877be9d1bde9fdf46/distro-1.3.0.tar.gz#sha256=224041cef9600e72d19ae41ba006e71c05c4dc802516da715d7fda55ba3d8742 (from https://pypi.org/simple/distro/), version: 1.3.0
  Using version 1.3.0 (newest of versions: 1.3.0, 1.2.0, 1.1.0, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.6.0, 0.5.0)
  Downloading from URL https://files.pythonhosted.org/packages/d2/42/3b059929a920cd9d4e91e7a5e35f0d2ed75211f8f4e877be9d1bde9fdf46/distro-1.3.0.tar.gz#sha256=224041cef9600e72d19ae41ba006e71c05c4dc802516da715d7fda55ba3d8742 (from https://pypi.org/simple/distro/)
  Running setup.py egg_info for package distro

    running egg_info
    creating pip-egg-info/distro.egg-info
    writing pip-egg-info/distro.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/distro.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/distro.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/distro.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/distro.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    

    reading manifest file 'pip-egg-info/distro.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'CHANGES'

    warning: no previously-included files matching '*.py[co]' found anywhere in distribution

    writing manifest file 'pip-egg-info/distro.egg-info/SOURCES.txt'
  Source in /storage/emulated/0/qpython/cache/pip-build/distro has version 1.3.0, which satisfies requirement distro
Installing collected packages: distro

  Running setup.py install for distro

    Running command /data/user/0/org.qpython.qpy3/files/bin/python-android5 -c "import setuptools;__file__='/storage/emulated/0/qpython/cache/pip-build/distro/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-pc0k6a-record/install-record.txt --single-version-externally-managed
    running install
    error: invalid Python installation: unable to open /sdcard/qpython/lib/python3.2/config-3.2m/Makefile (No such file or directory)

    Complete output from command /data/user/0/org.qpython.qpy3/files/bin/python-android5 -c "import setuptools;__file__='/storage/emulated/0/qpython/cache/pip-build/distro/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-pc0k6a-record/install-record.txt --single-version-externally-managed:

    running install

error: invalid Python installation: unable to open /sdcard/qpython/lib/python3.2/config-3.2m/Makefile (No such file or directory)

----------------------------------------

Command /data/user/0/org.qpython.qpy3/files/bin/python-android5 -c "import setuptools;__file__='/storage/emulated/0/qpython/cache/pip-build/distro/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-pc0k6a-record/install-record.txt --single-version-externally-managed failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build/distro

Exception information:
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/basecommand.py", line 107, in main
    status = self.run(options, args)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/commands/install.py", line 261, in run
    requirement_set.install(install_options, global_options)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/req.py", line 1166, in install
    requirement.install(install_options, global_options)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/req.py", line 589, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/util.py", line 612, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /data/user/0/org.qpython.qpy3/files/bin/python-android5 -c "import setuptools;__file__='/storage/emulated/0/qpython/cache/pip-build/distro/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-pc0k6a-record/install-record.txt --single-version-externally-managed failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build/distro

**Comment by riverfor** [comment]
Please switch to Python 3.6 from setting.
We will use Python 3.6 or above to replace the 3.2 in the future.

**Comment by Jsalaz1989** [comment]
I was having this issue when trying to install paho-mqtt on Python 3.2. I was sort of forced to use 3.2 instead of 3.6 because, when switching from Python 3.2 to 3.6 in the preferences, and trying to run the script, the console would say it couldn't locate python-for-android (import android) anymore. Python 3.2 didn't have this problem so I had to make this work for 3.2. However, on 3.2 it complained about the makefile, so I copied it from lib/python3.6/config-3.6m/Makefile to lib/python3.2/config-3.2m/Makefile and it now let me install paho-mqtt (which was the library generating the erro described by OP). 

Note that in my case the folder lib/python3.2 didn't exist yet on a fresh install of QPython3, so I just created it, along with /config-3.2m. Then I just copied the 3.6 makefile without any modifications and the console stopped complaining.
