### ISSUE TITLE
Error when using pip

### ISSUE THREAD

**Issue by okw95** [qpython-android/qpython#140]
Android Version: Android 8.1 Oreo
Phone Model: Asus Zenfone Max Pro M1
qpython version: qpython3 with python3.6

When I try to use pip to install some packages, qpython3 gave me error:  error: invalid Python installation: unable to open /sdcard/qpython/lib/python3.2/config-3.2m/Makefile (No such file or directory). So I tried to check the pip version with the command `pip --version` and get another strange error: can't find '_main_' module. Can you please investigate this issue as I could not run some scripts without installing necessary third party module? Thank You. @riverfor 

The error screenshot is at here:
![screenshot_20180828-095620](https://user-images.githubusercontent.com/40971481/44696688-2c0d5180-aaab-11e8-99a8-0fcb3d1247b9.png)
![screenshot_20180828-100233](https://user-images.githubusercontent.com/40971481/44696689-2c0d5180-aaab-11e8-9812-67b943d09bd1.png)

The full error log for package installation is at below:
[pip.log](https://github.com/qpython-android/qpython3/files/2326216/pip.log)

`------------------------------------------------------------
 run on Tue Aug 28 09:49:46 2018
Downloading/unpacking IP2LOCATION

  Running setup.py egg_info for package IP2LOCATION

    running egg_info
    writing pip-egg-info/IP2Location.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/IP2Location.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/IP2Location.egg-info/dependency_links.txt
    /data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/distutils/dist.py:257: UserWarning: Unknown distribution option: 'long_description_content_type'

      warnings.warn(msg)

    warning: manifest_maker: standard file '-c' not found
    

    reading manifest file 'pip-egg-info/IP2Location.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/IP2Location.egg-info/SOURCES.txt'
  Source in /storage/emulated/0/qpython/cache/pip-build/IP2LOCATION has version 8.0.3, which satisfies requirement IP2LOCATION
Installing collected packages: IP2LOCATION

  Running setup.py install for IP2LOCATION

    Running command /data/user/0/org.qpython.qpy3/files/bin/python-android5 -c "import setuptools;__file__='/storage/emulated/0/qpython/cache/pip-build/IP2LOCATION/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-_qok2t-record/install-record.txt --single-version-externally-managed
    running install
    /data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/distutils/dist.py:257: UserWarning: Unknown distribution option: 'long_description_content_type'

      warnings.warn(msg)

    error: invalid Python installation: unable to open /sdcard/qpython/lib/python3.2/config-3.2m/Makefile (No such file or directory)

    Complete output from command /data/user/0/org.qpython.qpy3/files/bin/python-android5 -c "import setuptools;__file__='/storage/emulated/0/qpython/cache/pip-build/IP2LOCATION/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-_qok2t-record/install-record.txt --single-version-externally-managed:

    running install

/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/distutils/dist.py:257: UserWarning: Unknown distribution option: 'long_description_content_type'

  warnings.warn(msg)

error: invalid Python installation: unable to open /sdcard/qpython/lib/python3.2/config-3.2m/Makefile (No such file or directory)

----------------------------------------

Command /data/user/0/org.qpython.qpy3/files/bin/python-android5 -c "import setuptools;__file__='/storage/emulated/0/qpython/cache/pip-build/IP2LOCATION/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-_qok2t-record/install-record.txt --single-version-externally-managed failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build/IP2LOCATION

Exception information:
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/basecommand.py", line 107, in main
    status = self.run(options, args)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/commands/install.py", line 261, in run
    requirement_set.install(install_options, global_options)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/req.py", line 1166, in install
    requirement.install(install_options, global_options)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/req.py", line 589, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/util.py", line 612, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /data/user/0/org.qpython.qpy3/files/bin/python-android5 -c "import setuptools;__file__='/storage/emulated/0/qpython/cache/pip-build/IP2LOCATION/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-_qok2t-record/install-record.txt --single-version-externally-managed failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build/IP2LOCATION
`

**Comment by okw95** [comment]
#113 #115  Seems like there are similar issues when installing packages using pip.
