### ISSUE TITLE
Unable to import numpy   QPython3

### ISSUE THREAD

**Issue by Fernandez-Miguel-A** [qpython-android/qpython#153]
i using Samsung J7 Neo
try to import numpy in QPython3 "ONLY" i get the next  error:

/data/user/0/org.qpython.qpy3/files/bin/qpython3-android5.sh && exit
in/qpython3-android5.sh && exit <
Python 3.6.4 (qpyc:3.6.4, Mar 12 2018, 13:00:23)
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>>
>>> import numpy
Traceback (most recent call last):
File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
from . import multiarray
ImportError: dlopen failed: library "libpython3.6m.so.1.0" not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
from . import add_newdocs
File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
from numpy.lib import add_newdoc
File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
from .type_check import *
File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
import numpy.core.numeric as _nx
File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed. Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control). Otherwise reinstall numpy.

Original error was: dlopen failed: library "libpython3.6m.so.1.0" not found

>>>

**Comment by riverfor** [comment]
Please upgrade to the newest QPython3 and install numpy-aipy3 from QPYPI please.
