### ISSUE TITLE
Can't install pyaudio

### ISSUE THREAD

**Issue by Odinukweze** [qpython-android/qpython#155]
I am trying to install pyaudio for speech recognition but am getting this error. 

-->
    Traceback (most recent call last):
      File "<string>", line 1, in <module>      File "/storage/emulated/0/qpython/cache/pip-build-5v9zjjkg/pyaudio/setup.py", line 111, in <module>
        long_description=__doc__.lstrip(),    AttributeError: 'NoneType' object has no attribute 'lstrip'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build-5v9zjjkg/pyaudio/
-->

Please I need help...

**Comment by frodo821** [comment]
I found the most basic matter is PYTHONOPTIMIZE environment variable set to 2 in /data/user/0/org.qpython.qpy/files/bin/init.sh

This flag enforces python interpreter to omit all extra information, for example, docstrings, assertions and byte-compiling.

Please remove the line, I ask to developers so. Because I couldn't find the file from related qpython-android github repositories.

**Comment by 1alikadri** [comment]
> I found the most basic matter is PYTHONOPTIMIZE environment variable set to 2 in /data/user/0/org.qpython.qpy/files/bin/init.sh
> 
> This flag enforces python interpreter to omit all extra information, for example, docstrings, assertions and byte-compiling.
> 
> Please remove the line, I ask to developers so. Because I couldn't find the file from related qpython-android github repositories.
> 
> P.S. The content of init.sh
> 
> ```shell
> #!/system/bin/sh
> export TERM=linux
> export PATH=/data/user/0/org.qpython.qpy/files/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
> export LD_LIBRARY_PATH=.:/data/user/0/org.qpython.qpy/files/lib/:/data/user/0/org.qpython.qpy/files/:/data/user/0/org.qpython.qpy/lib/
> export PYTHONHOME=/data/user/0/org.qpython.qpy/files
> export ANDROID_PRIVATE=/data/user/0/org.qpython.qpy/files
> export PYTHONPATH=/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/:/data/user/0/org.qpython.qpy/files/lib/python3.6/:/data/user/0/org.qpython.qpy/files/lib/python36.zip:/data/user/0/org.qpython.qpy/files/lib/notebook.zip:/data/user/0/org.qpython.qpy/files/lib/python3.6/qpyutil.zip:/data/user/0/org.qpython.qpy/files/lib/python3.6/lib-dynload/:/storage/emulated/0/qpython/lib/python3.6/site-packages/:
> export PYTHONOPTIMIZE=2
> export TMPDIR=/storage/emulated/0/qpython/cache
> export AP_HOST=127.0.0.1
> export AP_PORT=53119
> export AP_HANDSHAKE=0b84822c-f5cb-4f60-984e-8847d7ef57f5
> export ANDROID_PUBLIC=/storage/emulated/0/qpython
> export ANDROID_PRIVATE=/data/user/0/org.qpython.qpy/files
> export ANDROID_ARGUMENT=
> export PYTHONSTARTUP=/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/qpy.py
> export QPY_USERNO=b1ffcce0-f3db-4823-8bf4-27a6beb8df29
> export QPY_ARGUMENT={"adx_setting":"pa|marquee","adx_splash":"pa|full"}
> export PYTHONDONTWRITEBYTECODE=1
> export TMP=/storage/emulated/0/qpython/cache
> export ANDROID_APP_PATH=/storage/emulated/0/qpython
> export LANG=en_US.UTF-8
> export HOME=/data/user/0/org.qpython.qpy/files
> export ANDROID_DATA=/data
> export ANDROID_ROOT=/system
> ```

Can you explain me a little bit

**Comment by 1alikadri** [comment]
I mean how to export those

**Comment by JACKRJ528** [comment]
I have the same error here
