### ISSUE TITLE
打开app就报错了

### ISSUE THREAD

**Issue by sdqsdq** [qpython-android/qpython#162]
安装了最新的2.4.3，打开app就toast提示发生异常，已生成报错日志保存在xxx.log   日志如下:BOARD=sdm845
CPU_ABI2=armeabi
HOST=c4-miui-ota-bd45.bj
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@569a958
CPU_ABI=armeabi-v7a
PERMISSIONS_REVIEW_REQUIRED=false
DISPLAY=PKQ1.180729.001
SUPPORTED_ABIS=[Ljava.lang.String;@1a61ab1
FINGERPRINT=Xiaomi/dipper/dipper:9/PKQ1.180729.001/V10.1.2.0.PEACNFI:user/release-keys
PRODUCT=dipper
ID=PKQ1.180729.001
TYPE=user
SERIAL=unknown
DEVICE=dipper
MODEL=MI 8
MANUFACTURER=Xiaomi
USER=builder
BRAND=Xiaomi
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@e333e3b
HARDWARE=qcom
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/scheme/SchemeRegistry;
	at com.loopj.android.http.AsyncHttpClient.getDefaultSchemeRegistry(AsyncHttpClient.java:213)
	at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:179)
	at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:149)at org.qpython.qpy.utils.UpdateHelper.sendCrashLog(UpdateHelper.java:240)
	at org.qpython.qpy.utils.UpdateHelper.checkConfUpdate(UpdateHelper.java:159)
	at org.qpython.qpy.main.activity.HomeMainActivity.startMain(HomeMainActivity.java:106)
	at org.qpython.qpy.main.activity.HomeMainActivity.onCreate(HomeMainActivity.java:76)
	at android.app.Activity.performCreate(Activity.java:7200)
	at android.app.Activity.performCreate(Activity.java:7191)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6806)at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.conn.scheme.SchemeRegistry" on path: DexPathList[[zip file "/data/app/com.hipipal.qpyplus-9h5oNjeHeeX9OqGLNN8CJw==/base.apk"],nativeLibraryDirectories=[/data/app/com.hipipal.qpyplus-9h5oNjeHeeX9OqGLNN8CJw==/lib/arm, /data/app/com.hipipal.qpyplus-9h5oNjeHeeX9OqGLNN8CJw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClass............

**Comment by riverfor** [comment]
试试安装最新的版本 ？
