### ISSUE TITLE
ImportError: dlopen failed: library "libopenblas.so" not found

### ISSUE THREAD

**Issue by dajinsique** [qpython-android/qpython#163]
在Qpython 2.4.0下，代码第14行import 库函数如下:
"sklearn.model_selection import train_test_split"
报错如下：
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/scripts/skl_perceptron.py", line 14, in <module>rom 
    sklearn.model_selection import train_test_split
  File "/data/user/0/com.hipipal.qpyplus/files/lib/python2.7/site-packages/sklearn/model_selection/__init__.py", line 19, in <module>
    from ._validation import cross_val_score
  File "/data/user/0/com.hipipal.qpyplus/files/lib/python2.7/site-packages/sklearn/model_selection/_validation.py", line 31, in <module>
    from ..metrics.scorer import check_scoring, _check_multimetric_scoring
  File "/data/user/0/com.hipipal.qpyplus/files/lib/python2.7/site-packages/sklearn/metrics/__init__.py", line 34, in <module>
    from . import cluster
  File "/data/user/0/com.hipipal.qpyplus/files/lib/python2.7/site-packages/sklearn/metrics/cluster/__init__.py", line 20, in <module>
    from .unsupervised import silhouette_samples
  File "/data/user/0/com.hipipal.qpyplus/files/lib/python2.7/site-packages/sklearn/metrics/cluster/unsupervised.py", line 17, in <module>
    from ..pairwise import pairwise_distances_chunked
  File "/data/user/0/com.hipipal.qpyplus/files/lib/python2.7/site-packages/sklearn/metrics/pairwise.py", line 31, in <module>
    from .pairwise_fast import _chi2_kernel_fast, _sparse_manhattan
ImportError: dlopen failed: library "libopenblas.so" not found

同样的代码在Qpython 2.2.0上正常运行。

**Comment by danyalnawaz** [comment]
Gui of prime number,area of circle ,
