### ISSUE TITLE
Can't install numpy

### ISSUE THREAD

**Issue by Abhi210** [qpython-android/qpython#74]
Upon instLling numpy in qpython, I get following errors:

"

Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/storage/emulated/0/qpython/cache/build/numpy/setup.py", line 392, in <module>
        setup_package()
      File "/storage/emulated/0/qpython/cache/build/numpy/setup.py", line 384, in setup_package
        setup(**metadata)
      File "/storage/emulated/0/qpython/cache/build/numpy/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/storage/emulated/0/qpython/cache/build/numpy/setup.py", line 166, in configuration
        config.add_subpackage('numpy')
      File "/storage/emulated/0/qpython/cache/build/numpy/numpy/distutils/misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "/storage/emulated/0/qpython/cache/build/numpy/numpy/distutils/misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "/storage/emulated/0/qpython/cache/build/numpy/numpy/distutils/misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "numpy/setup.py", line 10, in configuration
        config.add_subpackage('core')
      File "/storage/emulated/0/qpython/cache/build/numpy/numpy/distutils/misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "/storage/emulated/0/qpython/cache/build/numpy/numpy/distutils/misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "/storage/emulated/0/qpython/cache/build/numpy/numpy/distutils/misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "numpy/core/setup.py", line 826, in configuration
        blas_info = get_info('blas_opt', 0)
      File "/storage/emulated/0/qpython/cache/build/numpy/numpy/distutils/system_info.py", line 380, in get_info
        return cl().get_info(notfound_action)
      File "/storage/emulated/0/qpython/cache/build/numpy/numpy/distutils/system_info.py", line 572, in get_info
        self.calc_info()
      File "/storage/emulated/0/qpython/cache/build/numpy/numpy/distutils/system_info.py", line 1638, in calc_info
        warnings.warn(AtlasNotFoundError.__doc__, stacklevel=2)
    TypeError: expected string or buffer"

**Comment by britoest** [comment]
Same issue

**Comment by riverfor** [comment]
Did you install numpy after having install AIPY (http://aipy.org) ?

**Comment by spanglerslive** [comment]
What is numpy?

**Comment by britoest** [comment]
@riverfor, I installed numpy through AIPY... and when I tried to import numpy, it gave me an error

Check this out:
https://github.com/qpython-android/qpython/issues/79
