### ISSUE TITLE
AIPY: all modules installed, and NumPy keeps giving error

### ISSUE THREAD

**Issue by britoest** [qpython-android/qpython#79]
I don't know what's really happening... all modules in AIPY tab depend on NumPy to work... I've installed NumPy through AIPY, but it seems it wasn't installed correctly

CHECK THIS OUT: when I try to import a module that is up to NumPy to work

<les/bin/qpython-root.sh && exit
Python 2.7.12 (default, Sep 28 2017, 11:17:05)
[GCC 4.9.x 20150123 (prerelease)] on linux4
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/scikit_learn_aipy-0.19.0-py2.7.egg/sklearn/__init__.py", line 134, in <module>
    from .base import clone
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/scikit_learn_aipy-0.19.0-py2.7.egg/sklearn/base.py", line 9, in <module>
    import numpy as np
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: Cannot load library: link_image[1891]: 11231 could not load needed library 'libopenblas.so' for 'multiarray.so' (link_image[1891]: 11231 could not load needed library 'libgfortran.so' for 'libopenblas.so' (reloc_library[1306]: 11231 cannot locate 'acoshf'...
))

>>>

===============================
When trying to import NumPy itself, the same error shows up. I don't know what to do to fix it. 

The console massage asks me to reinstall NumPy, that was I did, but I couldn't, cause NumPy cannot be installed by pip

By the way, there are libs that cannot be loaded (what the hell)... WHY?

**Comment by britoest** [comment]
Reletaed to some libs that cannot be loaded: I have root access, and I went to numpy folders and I found the multiarray.so lib... and I placed it in my system/lib folder, as well as qpython folders, but it didn't work. So I'd like to know WHY this lib cannot be loaded, even it's right there?

**Comment by riverfor** [comment]
What's your mobile's model and the android version . please ?

**Comment by britoest** [comment]
@riverfor, it's a Samsung Galaxy Win

Model: GT-I8552B
Android version: 4.1.2

**Comment by britoest** [comment]
I couldn't load <b style='color: red'>python</b> command because it couldn't load the lib libpython2.7.so... I found this lib in QPy's folder and placed it in system/lib - now i can use python cmd

By the way, i tried the same thing with these other libs (multiarray.so blah blah) but it seems not work

Try to update QPython with NumPy already installed and set up

And please, try to fix this issue... i wanna use NumPy

Thanks, britoest

**Comment by Abhi210** [comment]
Got same error. Tried everything that can be done. I think they should build app from scratch.

**Comment by sachgali** [comment]
Got same error :/

**Comment by xiaomile** [comment]
Got the same error a long time _(:з」∠)_

**Comment by Neurodynasoft** [comment]
Same error as OP.

I tried uninstalling everything and reinstalling again and the error persists. 

Galaxy E5 (SM-E500M)
Android 4.4.4

**Comment by GrejSegura** [comment]
I have the same problem. Is this resolved?
Samsung Galaxy J7
Android 7.0
