### ISSUE TITLE
QPython 2.0.9 fails to run previously working script

### ISSUE THREAD

**Issue by fpp-gh** [qpython-android/qpython#80]
I have a script that I use almost daily on my phone, it's been running for a couple of years on several models and versions of Android (currently 7).
Since I upgraded to QPython version 2.0.9, launching the same script fails in this way:
```
/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/scripts/apycsou.py" && exit
/qpython/scripts/apycsou.py" && exit     <
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/scripts/apycsou.py", line 5, in <module>
    import remi.gui as gui
  File "/storage/emulated/0/qpython/scripts/remi/__init__.py", line 1, in <module>
    from .gui import Widget, Button, TextInput, \
  File "/storage/emulated/0/qpython/scripts/remi/gui.py", line 21, in <module>
    from .server import runtimeInstances, update_event
  File "/storage/emulated/0/qpython/scripts/remi/server.py", line 20, in <module>
    from BaseHTTPServer import HTTPServer, BaseHTTPRequestHandler
  File "/data/user/0/org.qpython.qpy/files/lib/python27.zip/BaseHTTPServer.py", line 81, in <module>
  File "/data/user/0/org.qpython.qpy/files/lib/python27.zip/mimetools.py", line 6, in <module>
  File "/data/user/0/org.qpython.qpy/files/lib/python27.zip/tempfile.py", line 32, in <module>
  File "/data/user/0/org.qpython.qpy/files/lib/python27.zip/io.py", line 51, in <module>
ImportError: dlopen failed: cannot locate symbol "PyUnicodeUCS2_FromString" referenced by "/data/data/org.qpython.qpy/files/lib/python2.7/lib-dynload/_io.so"...
1|HWBLN-H:/ $
```
Is there anything I can do apart from trying to revert to an older version ?

**Comment by riverfor** [comment]
Which package did you install from QPYPI ?

Please reinstall these packages .
