### ISSUE TITLE
sl4a fails to run

### ISSUE THREAD

**Issue by cwgt** [qpython-android/qpython#81]
```
ripts/qsl4a_test.py" && exit      <
Traceback (most recent call last):
  File "/storage/sdcard0/qpython/scripts/qsl4a_test.py", line 10, in <module>
    droid = androidhelper.Android()
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/androidhelper/sl4a.py", line 34, in __init__
    self.conn = socket.create_connection(addr)
  File "/data/data/org.qpython.qpy/files/lib/python27.zip/socket.py", line 557, in create_connection
socket.gaierror: [Errno 9] servname not
 supported for ai_socktype
1|u0_a52@android:/ $
```

I remembered that it worked before. I ran the test and and it showed some widget (when I was testing it some days ago, it had the new ui ). now, I cant run any version, tried the old and the new version but it is not working.

**Comment by cwgt** [comment]
as my user complained, qpy3 and qpython3 (3.6.1) is also not working on my phone. there is a segmentation fault. can you please share the script to build cpython so that I will be able to test various version of cpython :) (I cant use current release of qpython3 because it cant ran 'requests' as it uses `u'   '` string)

**Comment by cwgt** [comment]
@riverfor can you please look into this problem.

**Comment by cwgt** [comment]
>Actively maintained apps that wish to target "L" must ship PIE executables or static executables. If an app wants to target ICS or below, it must also ship non-PIE executables or static executables. Even a simple "Hello world" program built with -fPIE -pie will segfault on ICS and GB.

@riverfor may be, this is the cause of the of the segfault

**Comment by cwgt** [comment]
closing as invalid, flashing stock rom fixes the problem
