### ISSUE TITLE
matplotlib-aipy

### ISSUE THREAD

**Issue by vanlexgaldino** [qpython-android/qpython#85]
Plot witch matplot-aipy in anroid.

**Comment by hutauf** [comment]
This is working fine for me. I am creating plots with matplotlib within qpython. Whats your precise problem?

**Comment by alfranbe** [comment]
I have a problem with qpython when I try to use matplotlib.
I'm unable to import literally anything from it.
Watch this:"

/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/matplotlib_aipy-2.1.0-py2.7.egg/matplotlib/__init__.py:901: UserWarning: could not find rc file; returning defaults
  warnings.warn(message)

"
The console prints this out every time I try to use matplotlib. I just don't know what to do.

**Comment by becshowalter** [comment]
I am having the same issue. 

This is my code :

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


x=[1,2,3,4]
y=[5,6,7,8]


plt.scatter(x,y)
only.title('testing matplotlib')
value=[2,4,6,8,10]
label=['one','two','three','four','five']
plt.xticks(value,label)
plt.show()

The error message I receive is the very same as alfranbe's.

**Comment by becshowalter** [comment]
I just tried installing matplotlib again and I'm having the same issue, but i did notice this little blurb popped up while downloading :

Could not find .egg-info directory in install record for matplotlib-aipy

But at the end the terminal says matplotlib-aipy was installed successfully.

**Comment by alfranbe** [comment]
I know it has been a long time since the last comment; but this error hasn't been solved yet.

See what happens now when I try to import pyplot from matplotlib:



/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh && exit
iles/bin/qpython-android5.sh && exit     <
Python 2.7.15 (qpyc:2.7.15, Aug 22 2018, 06:50:49) [BUILD WITH QPY-TOOLCHAIN (https://github.com/qpython-android) ] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from matplotlib import pyplot
/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/backports.functools_lru_cache_qpython-1.4-py2.7.egg/backports/__init__.py:1: UserWarning: Module backports was already imported from /data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/backports.functools_lru_cache_qpython-1.4-py2.7.egg/backports/__init__.py, but /data/data/org.qpython.qpy/files/lib/python2.7/site-packages/backports.ssl_match_hostname-3.5.0.1-py2.7.egg is being added to sys.path
  __import__("pkg_resources").declare_namespace(__name__)
/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/matplotlib_aipy-2.1.0-py2.7.egg/matplotlib/__init__.py:901: UserWarning: could not find rc file; returning defaults
  warnings.warn(message)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/matplotlib_aipy-2.1.0-py2.7.egg/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/matplotlib_aipy-2.1.0-py2.7.egg/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/matplotlib_aipy-2.1.0-py2.7.egg/matplotlib/artist.py", line 16, in <module>
    from .path import Path
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/matplotlib_aipy-2.1.0-py2.7.egg/matplotlib/path.py", line 25, in <module>
    from . import _path, rcParams
ImportError: dlopen failed: cannot locate symbol "__aeabi_d2uiz" referenced by "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/matplotlib_aipy-2.1.0-py2.7.egg/matplotlib/_path.so"...
>>>

**Comment by hhj000** [comment]
У меня абсолютно такая же ошибка. Видимо, придётся переходить с qpython на другие ide

**Comment by kpetrasek** [comment]
Has anyone solved this? I'm having similar problems with matplotlib-aipy.

**Comment by alfranbe** [comment]
> Has anyone solved this? I'm having similar problems with matplotlib-aipy.

Nothing has been solved as far as I know.
I keep having the same problems as if I was still in 2017.
(Minus the pandemic part of course)

**Comment by kpetrasek** [comment]
Thanks for the quick response -- your experience is what I expected to find -- that qpython has effectively been abandoned.  I'm going to drop it and try some of the other python-on-android solutions like Bee-ware or Kivy.

**Comment by Toutou-gamer** [comment]
For me, when I try to install matplotlib using qpypi (as pip requires python version >= 3.8) it says that I need version 3.6.8 or higher, and my current version is 3.6.6
I didn't find a way on internet to update python version on qpython3. I don't know if it's because my android version is 6.
Please if someone could help me in this then maybe I'd find a solution for this whole issue.

**Comment by Toutou-gamer** [comment]
why is this issue still open since 2017?!!!!
we are in 2022 and there's no solution yet!!!!

**Comment by Totozee** [comment]
I have this issues when i used the app Qpython 3L, but by using the app Pydroid3 it work fine

**Comment by Bzori** [comment]
> I have this issues when i used the app Qpython 3L, but by using the app Pydroid3 it work fine 

Is it available on play store?
