### ISSUE TITLE
Failure to install the SciPy Toolkit

### ISSUE THREAD

**Issue by zhanhang123** [qpython-android/qpython#98]
->pip install scipy
Downloading/unpacking scipy
  Running setup.py egg_info for package scipy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/storage/emulated/0/qpython/cache/build/scipy/setup.py", line 19, in <module>
        DOCLINES = __doc__.split("\n")
    AttributeError: 'NoneType' object has no attribute 'split'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/storage/emulated/0/qpython/cache/build/scipy/setup.py", line 19, in <module>

    DOCLINES = __doc__.split("\n")

AttributeError: 'NoneType' object has no attribute 'split'

----------------------------------------
Command python setup.py egg_info failed with error co

**Comment by zhanhang123** [comment]
anyone know what's the reason？

**Comment by hutauf** [comment]
If you need scipy, install it using aipy. Just search the google app store for aipy, download it, then you can install scipy using qpypi (inside qpython), no need for pip.
