### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by ramin1695** [qpython-android/qpython#99]
**Android 4.4 , Device is rooted**

### Console Text : 
Python 2.7.12 (default, Nov 21 2017, 21:49:35)
[GCC 4.9.x 20150123 (prerelease)] on linux4
### 》》》 pip.main(['install','--user','--upgrade','requests'])
Downloading/unpacking requests
    Downloading requests-2.18.4.tar.gz (126Kb): 126Kb downloaded
  Running setup.py egg_info for package requests
    Error [Errno 13] Permission denied while executing command python setup.py egg_info
Exception:
Traceback (most recent call last):
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/pip/req.py", line 980, in prepare_files
    req_to_install.run_egg_info()
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/pip/req.py", line 216, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/pip/__init__.py", line 226, in call_subprocess
    cwd=cwd, env=env)
  File "/data/data/org.qpython.qpy/files/lib/python27.zip/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/data/data/org.qpython.qpy/files/lib/python27.zip/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by ramin1695** [comment]
solved by updating Android version to 7
